blank_issues_enabled: false
contact_links:
  - name: Limux Community Support (Discord)
    url: https://discord.gg/KmajqZ7s
    about: Please ask Limux related questions in the game-engine-series thread.